### ISSUE TITLE
search for species observations using coordinate accuracy

### ISSUE THREAD

**Issue by DeboraArlt** [bioatlas/r-functionality#10]
is part of #8 

Current ALA4R has no such a priori selection (can only specify specific field values of form "indexedfield:value" to match with but no "larger than" or "smaller than"), user has to filter subsequently.
User wants to a priory select data by minimum accuracy of the coordinates.

Field for coordinate accuracy needs to be included in the SOLR index, current bioatlas SOLR scheme: https://github.com/bioatlas/ala-docker/blob/develop/solr7/mycores/biocache/conf/schema.xml

**Comment by DeboraArlt** [comment]
is related  #to filter species observations / facet search #8

**Comment by shahmanash** [comment]
The indexed fields can be accessed here

https://records.bioatlas.se/ws/index/fields?isMisc=false

Check out the following fields

```
coordinatePrecision
coordinatePrecision_p
coordinateUncertaintyInMeters
coordinateUncertaintyInMeters_p
```

The suffix  **_p** means that the field holds a processed value.

**Comment by sophiathirza** [comment]
An example of this type of query on the NBN: https://records.nbnatlas.org/occurrences/search?q=*%3A*&fq=coordinate_uncertainty:[1%20TO%2010]#tab_mapView

**Comment by DeboraArlt** [comment]
transferred to biodiversitydata-se/SBDI4R
