### ISSUE TITLE
sbdi4r pick filter function

### ISSUE THREAD

**Issue by aleruete** [bioatlas/r-functionality#14]
given that many fields are indexed, the way we decided to go is to create a function that allows the user to pick an indexed field and classes in there to quickly create a filter string

indexed field can include species lists, spatial layers

**Comment by aleruete** [comment]
@shahmanash @DeboraArlt 
I am trying to make sense of the filtering strings and have some doubts about how are things structured.

- the filter strings should be the same as the fileds listed e.g. "basis_of_record:..." or "data_resource_uid: ...", right?

- for the collections and institutions I can pass the institution, collection and data resource uid, but what is what in this hierarchy? Institution "in3" SLU has Artportalen as collection "co3" and Artportalen as data resource "dr5". What is the user interested in?

- for the layers, I have noticed some inconsistency in the naming that can manage to understand. The fields to filter by has for example "county" as a field name. But there is no layer called county just "Lan". Worldclim layers have names 10000 to 10018 but in fields they are called "cl100xx". Is there any correspondence between these search fields not to have to code them manually?

Ale

**Comment by aleruete** [comment]
I think I got it regarding the layers COntextual and environmental. One should only filter using the contextual right?

**Comment by shahmanash** [comment]
**the filter strings should be the same as the fileds listed e.g. "basis_of_record:..." or "data_resource_uid: ...", right?**

Yes, the filter strings are the ones listed here https://records.bioatlas.se/ws/index/fields . These are the fields predifined in the SOLR index where the search actually occur. However, when the data is processed , new fields can (and are) added, for example when the intersection with the layers are done, new fields corresponding to the layers are also added in the SOLR index.

**for the collections and institutions I can pass the institution, collection and data resource uid, but what is what in this hierarchy? Institution "in3" SLU has Artportalen as collection "co3" and Artportalen as data resource "dr5". What is the user interested in?**

The institution/collection concept relates more to the Natural history collections but is applied to the other data resources as well. The institutions, collections and datasets are managed in the
collectory app (https://collections.bioatlas.se/).

https://collections.bioatlas.se/ws/institution.json
https://collections.bioatlas.se/ws/collection.json

An institution can have a number of collections. The mapping of institution code and collection code to attribute the records to the collection/institution is done in the collectory. The datasets (dataresources) are the actual data provided to the system. A single dataresource can contain a number of collections in itself or a  collection might have been provided in a number of resources. 

https://collections.bioatlas.se/datasets/

It is difficult to say what the user might choose to filter their search, so search based on all the 3 attributions i.e. institution, collection and dataset are preferable.

**for the layers, I have noticed some inconsistency in the naming that can manage to understand. The fields to filter by has for example "county" as a field name. But there is no layer called county just "Lan". Worldclim layers have names 10000 to 10018 but in fields they are called "cl100xx". Is there any correspondence between these search fields not to have to code them manually?**

The field "county" that you mentioned is a DarwinCore term (https://dwc.tdwg.org/terms/#dwc:county). It is a string field that holds the value for **county** in the record. However, the layer "Lan" refers to this spatial layer (https://spatial.bioatlas.se/ws/layers/view/more/lan) .
Here are the layers currently available on the spatial portal (https://spatial.bioatlas.se/ws/layers/index).

In JSON : https://spatial.bioatlas.se/ws/layers

Each layer can be treated as fields when the data is processed. 

https://spatial.bioatlas.se/ws/fields

The fieldid corresponds to the layer id with the prefix "cl" or "el" added to the id of the layer based on its type (contextual or environmental)

https://spatial.bioatlas.se/ws/layers/shapes

https://spatial.bioatlas.se/ws/layers/grids

**Comment by aleruete** [comment]
thank you!
the question is then for layers, is it equivalent to filter a search for "&fq=cl10097:923967" being cl10097 counties and 923967 the pid för Uppsala?
The R search 
`
x <- occurrences(taxon="genus:Accipiter",
                 fq=c( "cl10097:923967"), 
                 download_reason_id=10)
`
return no observation, while the web search 
https://records.bioatlas.se/ws/occurrences?q=Accipiter&reasonTypeId=10&fq=cl10097:923967
return "totalRecords": 88777589

**Comment by shahmanash** [comment]
https://records.bioatlas.se/ws/occurrences/search?q=cl10097:%22Uppsala%22&fq=genus:%22Accipiter%22

33468 records
