### ISSUE TITLE
No indexed fields

### ISSUE THREAD

**Issue by aleruete** [bioatlas/r-functionality#19]
It seems no field is indexed or stored, producing some errors on functions depending on indexed fields. 
https://records.bioatlas.se/ws/index/fields 
all Indexed = FALSE for all fields, same for stored

**Comment by shahmanash** [comment]
https://records.bioatlas.se/ws/index/fields/?indexed=true&stored=true

The above URL returns the fields indexed and stored

**Comment by aleruete** [comment]
I had chached a somewhat older version of these fields where there were not indexed. FIXED!
