### ISSUE TITLE
search by observation type

### ISSUE THREAD

**Issue by DeboraArlt** [bioatlas/r-functionality#2]
is part of #8 

Observations labelled as Not rediscovered, non-natural occurrence should be possible for the user to filter out. 
Provide this filtering option using data fields (dwc terms): IsNeverFoundObservation, IsNotRediscoveredObservation, IsNaturalOccurrence, IsPositiveObservation.

Fields need to be included in the SOLR index, current bioatlas SOLR scheme: https://github.com/bioatlas/ala-docker/blob/develop/solr7/mycores/biocache/conf/schema.xml

**Comment by shahmanash** [comment]
The 4 terms mentioned are not standard DarwinCore terms (https://www.slu.se/en/subweb/swedish-lifewatch/guides/data-management/data-providers/slu-swedish-species-information-center/dataservices/speciesobservationservice/)  and could not be found here https://github.com/tdwg/dwc/tree/master/dist

However if in a source CSV there are some additional columns that are not defined in DarwinCore standard, they are automatically added into a JSON stored in the Cassandra column:

`miscProperties`

To add them to the SOLR index, the following property needs to be set in the biocache-store config file:

`additional.fields.to.index=myField1,myField2,myField3`

or to the fle `additionalFields.list` if using `IndexLocalNode` function.

**Comment by DeboraArlt** [comment]
issue transferred to  biodiversitydata-se/SBDI4R
