### ISSUE TITLE
sbdi4r field guides ws

### ISSUE THREAD

**Issue by aleruete** [bioatlas/r-functionality#20]
Is there any ws similar to https://fieldguide.ala.org.au/?
there is a function based on this service, but the analos service for sweden doesnt seem to exist.
Shall I strike this function?

**Comment by shahmanash** [comment]
The fieldguide module has not been implemented in Bioatlas since there has not been any request to do so.

**Comment by aleruete** [comment]
ok, so I "hide" this function in case it comes in the future

**Comment by DeboraArlt** [comment]
ok. good to keep it "hidden" just in case it comes in the future. although won't be soon future. as long as sbdi is financed by VR and VR's request is to only serve academic research the 'field guide module' is out of this focus.
