### ISSUE TITLE
sbdi4r results for multiple polygons

### ISSUE THREAD

**Issue by DeboraArlt** [bioatlas/r-functionality#4]
Similar to grid functions the user wants to get results for multiple polygons.

In the current Spatial Portal the user can draw or import polygons, also multiple ones, but results (e.g. Area report with no. of species, no. of occurrences per taxon, etc.) can only be displayed/retrieved for single polygons.
Similar to using a spatial grid the user wants to get aggregated statistics for multiple polygons (i.e. use polygons in the same way as grid cells).

Ideally one would want to have this functionality in the web portal (Spatial portal) - because the principle is the same/similar to working with grid cells, e.g. points-to-grid tool ("points-to-polygon").
An alternative is to provide this functionality through R functions.

For provided layers they will be adedd to the SOLR index of indexed fields and hence can be easily searched. That measn for provided layers solution will be based on #14.
For user-imported (or drawn) polygons we need a different solution.

**Comment by aleruete** [comment]
ALA4R::specieslist(wkt=wkt, fq="state_conservation:*") 
where wkt is the polygon. 
Potentially: disolved polygon --> intersect
or less efficient:iterative over all polygons

**Comment by aleruete** [comment]
So I now added an example on how to make summaries over polygones (a grid in this case) after downloading the observations. The alternative is to get summaries via a faceted search for a grid or indexed layer (in progress).
