### ISSUE TITLE
sbdi4r: Select occurrences from different data sources

### ISSUE THREAD

**Issue by DeboraArlt** [bioatlas/r-functionality#9]
Enable a priori selection of data according to data source. Current ALA4R retrieves all and data are typically filtered subsequently. But occurrence() allows a 'fq' optional string for specifying filters to be applied to the original query, of the form "indexedfield:value" - test whether this is possible to use as "datasource:Artportalen".

relies on #14

**Comment by aleruete** [comment]
Done via filter query fq, and list of dataResources listed in collections.

**Comment by aleruete** [comment]
Will be covered by helper function pickFilter()
